### PR TITLE
Add test for common backup archive files

### PR DESCRIPTION
**Pull request by timonegk**
This pull request adds a simple check for common backup archive files. The list of files consists of `backup.zip`, `www.zip`, `wwwroot.zip`, `backup.tar.gz`, `www.tar.gz` and `wwwroot.tar.gz` (the file names were inspired by https://github.com/unamer/CTFHelper/blob/master/CTFhelper.py#L82). 
Even though these files do not exist very often (approx. 0.1% of the checked hostnames), the security implications of a found backup are huge. A backup archive does not only contain source code which provides an insight into the site structure but it may also contain secret keys, database passwords or database dumps. Additionally, the test is inexpensive requiring only six HTTP requests.

### CODE REVIEW

**Comment by hannob** [comment]
This sounds reasonable, but I wonder if there's some justification for the filenames. It looks a bit arbitrary. Did you do scans and can give a distribution of how common these filenames are? did you see attacking attempts in webserver logs?

**Comment by timonegk** [comment]
The file names are just the ones that I found in the above mentioned file. A scan on one million websites reveals the following name distribution:

`backup.zip`: 318
`www.zip`: 156
`wwwroot.zip`: 108
`backup.tar.gz`: 95
`www.tar.gz`: 16

Since `wwwroot.tar.gz` has not be found, it should probably be removed from the list.

Additionally, I just had the idea to add the files `[hostname].zip` and `[hostname].tar.gz`. From the small amount of scans that I already ran with these additional files, they seem to occur more often than the ones specified above. I will add the according commit to this pull request.

**Comment by hannob** [comment]
@timonegk can you contact me directly, e.g. via email? (find my contact info here https://hboeck.de/en/contact.html )

**Comment by rugk** [comment]
Considering https://www.golem.de/news/websicherheit-datenlecks-durch-backup-zip-1904-140564.html has been published now, I guess you can also merge this here? :smiley:

**Comment by beli3ver** [comment]
Like @rugk I think so too.
Please merge it to the test.

**Comment by hannob** [comment]
I'll merge this for now so you get credits in the git history, but I'll replace it with a somewhat different test code and will start by using backup.* and will gradually test other filenames and decide whether I'll add them.

**Comment by hannob** [comment]
FYI I renamed the test to backup_archive for consistency (all other tests are singular and the messages were as well). Also opened an issue for further filenames: https://github.com/hannob/snallygaster/issues/41
I'm running tests with different filenames and will add them as they seem worthy.

**Comment by michael-k** [comment]
> all other tests are singular 

What about `test_backupfiles` and `test_phpwarnings`?  Should they be renamend as well?

**Pull request merged**
