### PR TITLE
Test: Nette Framework - config.neon

### PR DESCRIPTION
**Pull request by lynt-smitka**
Nette (https://nette.org/en/) is very popular web PHP framework.  It stores its config in the config.neon file. This file should not be accessible via browser, but many sites don't follow best practices.

### CODE REVIEW

**Comment by hannob** [comment]
This looks interesting, but please remove the unrelated phpinfo part. (You may open another PR for that one.) One feature per pull request only.

**Comment by lynt-smitka** [comment]
I'm sorry I made multiple changes and accidentally pushed them all... Unrelated are removed, I will send another PR with phpinfo().

**Comment by hannob** [comment]
I ran some tests with this check.

I haven't found a single real hit, however it produces many false positives (these appear when a site shits some html on every request to a nonexistent file and this contains "application:" for some reason).

So for merging these tests I'd need to know how relevant this is and we'd need to fix it so it doesn't produce such a large number of false positives. Also do you have any references for this problem, i.e. public documentation describing the kind of misconfiguration or reports about sites being vulnerable to it?

**Comment by hannob** [comment]
So we can make the test not create lots of false positives by checking the presence of 'nette:':
```
@DEFAULT
def test_nette_config(url):
    for fn in ["app/config/config.neon", "app/config.neon", "config.neon"]:
        r = fetcher(url + "/" + fn)
        if 'nette:' in r and 'application:' in r:
            pout("nette_config_neon", url + "/" + fn)
```

However I did a scan on the Alexa Top 1 Million and I got one hit and it also didn't contain anything interesting. It looks to me without further justification I won't add that check.

**Pull request closed without merging**
