### PR TITLE
Add minimalistic docker image

### PR DESCRIPTION
**Pull request by pieterlange**
Makes the project easy to run with some minimum level of isolation.

Alpine base image keeps things small & safe:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
snallygaster        latest              b41c47c92bfc        5 minutes ago       98.2MB
```

Usage:
```
$ docker run -ti --rm snallygaster /app/snallygaster --help
usage: snallygaster [-h] [-t TESTS] [--useragent USERAGENT] [--nowww]
                    [--nohttp] [--nohttps] [-i] [-n] [-j] [-d]
                    [hosts [hosts ...]]

positional arguments:
  hosts                 hostname to scan

optional arguments:
  -h, --help            show this help message and exit
  -t TESTS, --tests TESTS
                        comma-separated tests to run.
  --useragent USERAGENT 
                        User agent to send
  --nowww               skip scanning www.[host]
  --nohttp              Don't scan http
  --nohttps             Don't scan https
  -i, --info            Enable all info tests (no bugs/security
                        vulnerabilities)
  -n, --noisy           show noisy messages that indicate boring bugs, but no
                        security issue
  -j, --json            produce JSON output
  -d, --debug           show detailed debugging info
```

If you're happy with this it's easy to publish this on the docker hub or on quay.io

### CODE REVIEW

**Comment by hannob** [comment]
ok. Is there a reason not to publish it on both plattforms?

**Comment by pieterlange** [comment]
I publish on both platforms myself so thats fine actually.

Thanks for the project & research!

**Comment by hannob** [comment]
Does that look good?
https://hub.docker.com/r/hannob/snallygaster/

**Comment by hannob** [comment]
quay seems to be only available if you pay, except for a free trial. So I guess we leave it with docker hub.

**Comment by pieterlange** [comment]
Public repo's are free on quay and it looks like you'll have to manually trigger some builds on the docker hub (repo's are linked, but no builds yet)

**Pull request merged**
